version: '3.8'

services:
  ai-pricing-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-pricing-api
    restart: unless-stopped
    ports:
      - "8050:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./faiss_index:/app/faiss_index
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - ai-pricing-network

networks:
  ai-pricing-network:
    driver: bridge 