version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: ai-pricing-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./faiss_index:/app/faiss_index
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - FRED_API_KEY=${FRED_API_KEY}
      - INFURA_ENDPOINT=${INFURA_ENDPOINT}
      - OPENSEA_API_KEY=${OPENSEA_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - ai-pricing-network

networks:
  ai-pricing-network:
    driver: bridge
